export const CHATROOM_LIST_REQUEST = 'CHATROOM_LIST_REQUEST';
export const CHATROOM_LIST_SUCCESS = 'CHATROOM_LIST_SUCCESS';
export const CHATROOM_LIST_FAIL = 'CHATROOM_LIST_FAIL';

export const CHATROOM_CREATE_REQUEST = 'CHATROOM_CREATE_REQUEST';
export const CHATROOM_CREATE_SUCCESS = 'CHATROOM_CREATE_SUCCESS';
export const CHATROOM_CREATE_FAIL = 'CHATROOM_CREATE_FAIL';
export const CHATROOM_CREATE_RESET = 'CHATROOM_CREATE_RESET';
